x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:3.0.0}
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-meta/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins
    - ./logs:/opt/airflow/logs
  depends_on:
    &airflow-common-depends-on
    postgres-meta:
      condition: service_healthy

services:
  postgres-meta:
    image: postgres:15-alpine
    container_name: airflow_postgres_meta
    environment:
      POSTGRES_USER:     airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB:       airflow
    volumes:
      - postgres_meta_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    command:
      - bash
      - -c
      - |
        set -e
        echo "Ejecutando migraciones de base de datos..."
        airflow db migrate
        echo "Creando usuario admin (si no existe)..."
        airflow users create \
          --username admin \
          --firstname admin \
          --lastname admin \
          --role Admin \
          --email admin@example.com \
          --password admin || true
        echo "Init completado correctamente"
    restart: "no"

  airflow-api-server:
      <<: *airflow-common
      container_name: airflow_api_server
      command: api-server
      ports:
        - "8080:8080"
      healthcheck:
        test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/monitor/health"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s
      restart: unless-stopped
      depends_on:
        <<: *airflow-common-depends-on
        airflow-init:
          condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-dag-processor:
    <<: *airflow-common
    container_name: airflow_dag_processor
    command: dag-processor
    restart: unless-stopped
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

volumes:
  postgres_meta_data:
    driver: local